### ISSUE TITLE
led's on shabadge?

### ISSUE THREAD

**Issue by morris2009** [bitlair/esphome-configs#1]
Hi,
I am very excited to see someone else is using the shabadge2017 in an ESP home project. I also managed to install ESPhome on my old shabadge and only had some basics, with your yaml I could enable some additional features.

What I am not able to get working are the LEDs that are soldered to the board.
I noticed you have a 'light' section in your YAML, I copied this, but can't get it to work. My home assistant doesn't even see a light entity from the esphome device.

Do you have any hints or tips to point me in the right direction?
Tnx!

**Comment by morris2009** [comment]
I was eventually able to get it to work, so ignore my reach out for help.
If you ever need the config I used just let me know.

**Comment by polyfloyd** [comment]
Could you post your config here?

**Comment by morris2009** [comment]
Sure.
This is what I now have for the LED's

```
light:
  - platform: neopixelbus
    type: GRBW
    variant: sk6812
    pin: 32
    num_leds: 6
    name: badge_leds
    icon: mdi:ledstrip
    effects:
      - addressable_rainbow: 
      - addressable_scan:
      - addressable_random_twinkle:
      - addressable_twinkle:
      - addressable_fireworks:
```
